#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_quizz:
  path: /
  controller: App\Controller\ReactController::index
#  http://vps799626.ovh.net:4000/:
#     type: redirect
#     to: https://www.vps799626.ovh.net:4000/
